//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CangsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessRight
    {
        public int rightNum { get; set; }
        public int employeeID { get; set; }
        public int levelNum { get; set; }
    
        public virtual AccessLevel AccessLevel { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
