//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CangsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerLog
    {
        public int logID { get; set; }
        public string cusLogNumber { get; set; }
        public string cusLogAddress { get; set; }
        public string cusLogLastName { get; set; }
        public string cusLogFirstName { get; set; }
        public string cusLogMiddleName { get; set; }
        public System.DateTime cusLogTime { get; set; }
        public int employeeID { get; set; }
        public int customerID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
