//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CangsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.UpdateOrderStatus = new HashSet<UpdateOrderStatus>();
        }
    
        public int orderID { get; set; }
        public string orderDate { get; set; }
        public string orderTotal { get; set; }
        public string orderStatus { get; set; }
        public string orderRemarks { get; set; }
        public string location { get; set; }
        public string orderTime { get; set; }
        public string packaging { get; set; }
        public int customerID { get; set; }
        public int isDeleted { get; set; }
        public decimal cashTendered { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UpdateOrderStatus> UpdateOrderStatus { get; set; }
    }
}
