//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CangsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int transID { get; set; }
        public string ordetQuantity { get; set; }
        public string ordetPrice { get; set; }
        public string ordetSubtotal { get; set; }
        public int orderID { get; set; }
        public int itemID { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
