//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CangsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateDetail
    {
        public int tempDetailID { get; set; }
        public int temdeQuantity { get; set; }
        public int itemID { get; set; }
        public int templateID { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Template Template { get; set; }
    }
}
