//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CangsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpdateItem
    {
        public int updateID { get; set; }
        public System.DateTime logDate { get; set; }
        public int logQuantity { get; set; }
        public decimal logPrice { get; set; }
        public int itemID { get; set; }
        public int employeeID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Item Item { get; set; }
    }
}
