//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CangsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpdateOrderStatus
    {
        public int statusID { get; set; }
        public string orstatStatus { get; set; }
        public string orstatRemarks { get; set; }
        public System.DateTime orstatDate { get; set; }
        public int employeeID { get; set; }
        public int orderID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Order Order { get; set; }
    }
}
